app:
  build: .
  volumes:
   - .:.:rw
  links:
    - mongo
    - redis
  ports:
    - "3000:3000"

mongo:
  image: mongo
  ports:
  - "27017:27017"
  - "28017:28017"

redis:
  image: redis
  ports:
    - "6379:6379"